spring.application.name=Consumer Service

#huggingFace
hugging.face.text-generator.api=https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-large
hugging.face.api.key=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
#rabbit
spring.rabbitmq.host=beaver-01.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=arfwhhhi
spring.rabbitmq.password=ugLhbJKgaTFFkpHsJDt35Bx6LRSaw27U
spring.rabbitmq.virtual-host=arfwhhhi
#database
spring.datasource.url=jdbc:postgresql://everest.liara.cloud:33934/postgres
spring.datasource.username=root
spring.datasource.password=m5jzUFz0ULnJlgSu1YiO6rUN
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#liara configs
liara.bucket.name=mybucketstorage
liara.objstore.endpoint=https://storage.c2.liara.space
liara.access.key=s1munpaa38hqnkpo
liara.secret.key=e1155880-5e4b-4481-afbd-856c07449be9
#server
server.port=8082